# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: mkxp-z
    MAKEFILE: Makefile.libretro
  needs:
    - job: stage1
      artifacts: true

.miniforge:
  script:
    - wget -O ~/Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
    - bash ~/Miniforge3.sh -b -p ~/miniforge3
    - source ~/miniforge3/etc/profile.d/conda.sh
    - conda install -y ${MINIFORGE_PACKAGES}
    - export PATH="$HOME/miniforge3/bin:$PATH"

.deps-linux:
  extends:
    - .miniforge
  variables:
    MINIFORGE_PACKAGES: git meson cmake

.deps-macos:
  script:
    - brew install -q git meson cmake

.deps-windows:
  script:
    - pacman --noconfirm -S git meson cmake

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Windows msvc10 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-msvc10-msys2.yml'

  # Windows msvc10 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-msvc10-msys2.yml'

  # Windows msvc05 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-msvc05-msys2.yml'

  # DJGPP
  - project: 'libretro-infrastructure/ci-templates'
    file: '/djgpp-static.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # MacOS PowerPC 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-ppc.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  # MacOS ARM 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-arm64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-make.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-arm64.yml'

  # iOS (armv7)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios9.yml'

  ################################## CONSOLES ################################
  # PlayStation Portable
  - project: 'libretro-infrastructure/ci-templates'
    file: '/psp-static.yml'

  # PlayStation Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'

  # PlayStation2
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ps2-static.yml'

  # PlayStation3
  - project: 'libretro-infrastructure/ci-templates'
    file: '/psl1ght-static.yml'

  # PlayStation 4
  - project: 'libretro-infrastructure/ci-templates'
    file: '/orbis-static.yml'

  # Nintendo 3DS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ctr-static.yml'

  # Nintendo GameCube
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ngc-static.yml'

  # Nintendo Wii
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wii-static.yml'

  # Nintendo WiiU
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static.yml'

  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

  # tvOS (AppleTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-arm64.yml'

  # OpenDingux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-mips32.yml'

  # OpenDingux (ARM)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-arm32.yml'

  #################################### MISC ##################################
  # Emscripten
  - project: 'libretro-infrastructure/ci-templates'
    file: '/emscripten-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################

stage1:
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu
  stage: build-prepare
  variables:
    MINIFORGE_PACKAGES: clang clangxx make autoconf automake libtool zip binaryen universal-ctags ruby
  script:
    - !reference [.miniforge, script]
    - if [ ! -e /usr/bin/grep ]; then ln -s /bin/grep /usr/bin/grep; fi
    - if [ ! -e /usr/bin/sed ]; then ln -s /bin/sed /usr/bin/sed; fi
    - curl -Lo ~/wasi-sdk.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-21/wasi-sdk-21.0-linux.tar.gz
    - mkdir ~/wasi-sdk
    - tar xzf ~/wasi-sdk.tar.gz -C ~/wasi-sdk --strip-components=1
    - rm ~/wasi-sdk.tar.gz
    - cd libretro
    - CLICOLOR_FORCE=1 make -j $(nproc) WASI_SDK="$HOME/wasi-sdk" NATIVE_CC=clang NATIVE_CXX=clang++ ZLIB_PATH="$HOME/miniforge3" LIBYAML_PATH="$HOME/miniforge3" OPENSSL_PATH="$HOME/miniforge3"
  artifacts:
    paths:
      - libretro/build/libretro-stage1/
    expire_in: 1 day

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .deps-windows
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  script:
    - !reference [.deps-windows, script]
    - !reference [.libretro-windows-x64-mingw-make-default, script]

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .deps-windows
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  script:
    - !reference [.deps-windows, script]
    - !reference [.libretro-windows-i686-mingw-make-default, script]

# Windows msvc10 64-bit
#libretro-build-windows-msvc10-x64:
#  extends:
#    - .libretro-windows-x64-msvc10-msys2-make-default
#    - .core-defs

# Windows msvc10 32-bit
#libretro-build-windows-msvc10-i686:
#  extends:
#    - .libretro-windows-i686-msvc10-msys2-make-default
#    - .core-defs

# Windows msvc05 32-bit
#libretro-build-windows-msvc05-i686:
#  extends:
#    - .libretro-windows-i686-msvc05-msys2-make-default
#    - .core-defs

# DJGPP
#libretro-build-djgpp-i586:
#  extends:
#    - .deps-linux
#    - .libretro-djgpp-static-retroarch-master
#    - .core-defs
#  needs:
#    - !reference [.libretro-djgpp-static-retroarch-master, needs]
#    - !reference [.core-defs, needs]
#  script:
#    - !reference [.deps-linux, script]
#    - !reference [.libretro-build-djgpp-i586, script]

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .deps-linux
    - .libretro-linux-x64-make-default
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-linux-x64-make-default, script]

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .deps-linux
    - .libretro-linux-i686-make-default
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-linux-i686-make-default, script]

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .deps-macos
    - .libretro-osx-x64-make-default
    - .core-defs
  script:
    - !reference [.deps-macos, script]
    - !reference [.libretro-osx-x64-make-default, script]

# MacOS ARM 64-bit
libretro-build-osx-arm64:
  extends:
    - .deps-macos
    - .libretro-osx-arm64-make-default
    - .core-defs
  script:
    - !reference [.deps-macos, script]
    - !reference [.libretro-osx-arm64-make-default, script]

# MacOS PowerPC 32-bit
#libretro-build-osx-ppc:
#  extends:
#    - .deps-macos
#    - .libretro-osx-ppc-make-default
#    - .core-defs
#   script:
#   - !reference [.deps-macos, script]
#   - !reference [.libretro-osx-ppc-make-default, script]

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .deps-linux
    - .libretro-android-make-armeabi-v7a
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-android-make-armeabi-v7a, script]

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .deps-linux
    - .libretro-android-make-arm64-v8a
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-android-make-arm64-v8a, script]

# Android 64-bit x86
android-x86_64:
  extends:
    - .deps-linux
    - .libretro-android-make-x86_64
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-android-make-x86_64, script]

# Android 32-bit x86
android-x86:
  extends:
    - .deps-linux
    - .libretro-android-make-x86
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-android-make-x86, script]

# iOS
libretro-build-ios-arm64:
  extends:
    - .deps-macos
    - .libretro-ios-arm64-make-default
    - .core-defs
  script:
    - !reference [.deps-macos, script]
    - !reference [.libretro-ios-arm64-make-default, script]

# iOS (armv7) [iOS 9 and up]
libretro-build-ios9:
  extends:
    - .deps-macos
    - .libretro-ios9-make-default
    - .core-defs
  script:
    - !reference [.deps-macos, script]
    - !reference [.libretro-ios9-make-default, script]

# tvOS
libretro-build-tvos-arm64:
  extends:
    - .deps-macos
    - .libretro-tvos-arm64-make-default
    - .core-defs
  script:
    - !reference [.deps-macos, script]
    - !reference [.libretro-tvos-arm64-make-default, script]

################################### CONSOLES #################################
# PlayStation Portable
#libretro-build-psp:
#  extends:
#    - .deps-linux
#    - .libretro-psp-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-psp-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-psp-static-retroarch-master, script]

# PlayStation Vita
#libretro-build-vita:
#  extends:
#    - .deps-linux
#    - .libretro-vita-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-vita-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-vita-static-retroarch-master, script]

# PlayStation2
#libretro-build-ps2:
#  extends:
#    - .deps-linux
#    - .libretro-ps2-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-ps2-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-ps2-static-retroarch-master, script]

# PlayStation3
#libretro-build-psl1ght:
#  extends:
#    - .deps-linux
#    - .libretro-psl1ght-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-psl1ght-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-psl1ght-static-retroarch-master, script]

# PlayStation 4
#libretro-build-orbis:
#  extends:
#    - .deps-linux
#    - .libretro-orbis-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-orbis-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-orbis-static-retroarch-master, script]

# Nintendo 3DS
#libretro-build-ctr:
#  extends:
#    - .deps-linux
#    - .libretro-ctr-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-ctr-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-ctr-static-retroarch-master, script]

# Nintendo GameCube
#libretro-build-ngc:
#  extends:
#    - .deps-linux
#    - .libretro-ngc-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-ngc-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-ngc-static-retroarch-master, script]

# Nintendo Wii
#libretro-build-wii:
#  extends:
#    - .deps-linux
#    - .libretro-wii-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-wii-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-wii-static-retroarch-master, script]

# Nintendo WiiU
#libretro-build-wiiu:
#  extends:
#    - .libretro-wiiu-static-retroarch-master
#    - .core-defs
#   needs:
#   - !reference [.libretro-wiiu-static-retroarch-master, needs]
#   - !reference [.core-defs, needs]

# Nintendo Switch
libretro-build-libnx-aarch64:
  extends:
    - .deps-linux
    - .libretro-libnx-static-retroarch-master
    - .core-defs
  needs:
    - !reference [.libretro-libnx-static-retroarch-master, needs]
    - !reference [.core-defs, needs]
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-libnx-static-retroarch-master, script]

# OpenDingux
libretro-build-dingux-mips32:
  extends:
    - .deps-linux
    - .libretro-dingux-mips32-make-default
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-dingux-mips32-make-default, script]

# OpenDingux Beta
libretro-build-dingux-odbeta-mips32:
  extends:
    - .deps-linux
    - .libretro-dingux-odbeta-mips32-make-default
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-dingux-odbeta-mips32-make-default, script]

# OpenDingux Beta
#libretro-build-rs90-odbeta-mips32:
#  extends:
#    - .deps-linux
#    - .libretro-rs90-odbeta-mips32-make-default
#    - .core-defs
#   script:
#   - !reference [.deps-linux, script]
#   - !reference [.libretro-rs90-odbeta-mips32-make-default, script]

# Miyoo
libretro-build-miyoo-arm32:
  extends:
    - .deps-linux
    - .libretro-miyoo-arm32-make-default
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-miyoo-arm32-make-default, script]

# RetroFW
libretro-build-retrofw-mips32:
  extends:
    - .deps-linux
    - .libretro-retrofw-mips32-make-default
    - .core-defs
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-retrofw-mips32-make-default, script]

#################################### MISC ##################################
# Emscripten
libretro-build-emscripten:
  extends:
    - .deps-linux
    - .libretro-emscripten-static-retroarch-master
    - .core-defs
  needs:
    - !reference [.libretro-emscripten-static-retroarch-master, needs]
    - !reference [.core-defs, needs]
  script:
    - !reference [.deps-linux, script]
    - !reference [.libretro-emscripten-static-retroarch-master, script]
