option('mri_version', type: 'string', value: '3.1', description: 'Version of MRI to link with')
option('mri_includes', type: 'string', value: '', description: 'Ruby manual include path')
option('mri_libpath', type: 'string', value: '', description: 'Ruby manual lib path')
option('mri_library', type: 'string', value: '', description: 'Ruby manual link name')
option('force32', type: 'boolean', value: false, description: 'Force compiler to build a 32-bit executable')

option('cxx11_experimental', type: 'boolean', value: false, description: 'Toggles between using ghc/filesystem or C++11 <experimental/filesystem>')
option('shared_fluid', type: 'boolean', value: true, description: 'Dynamically link fluidsynth at build time')
option('cjk_fallback_font', type: 'boolean', value: false, description: 'Use WenQuanYi Micro Hei as the fallback font')
option('use_miniffi', type: 'boolean', value: true, description: 'Enable MiniFFI Ruby module (Win32API)')
option('workdir_current', type: 'boolean', value: false, description: 'Keep current directory on startup')

option('windows_resource_directory', type: 'string', value: 'windows', description: 'Path to Windows EXE resource directory')

option('static_executable', type: 'boolean', value: true, description: 'Build a static executable (Windows-only)')
option('appimagekit_path', type: 'string', value: '', description: 'Path to AppImageTool, used for building AppImages')
option('appimage', type: 'boolean', value: false, description: 'Whether to install to an AppImage or just copy everything')
option('steamworks_path', type: 'string', value: '', description: 'Path to Steamworks SDK')
option('steam_appid', type: 'string', value: '', description: 'Steam AppID. Set this to use SteamAPI_RestartAppIfNecessary')
option('steamshim_debug', type: 'boolean', value: false, description: 'Whether to show Steamshim debug messages in the console')

option('aarch64_neon', type: 'feature', value: 'auto', description: 'Enable support for NEON intrinsics when building for 64-bit ARM architecture')
option('arm_armv6', type: 'feature', value: 'auto', description: 'Enable support for ARMv6 intrinsics when building for 32-bit ARM architecture')
option('arm_neon', type: 'feature', value: 'disabled', description: 'Enable support for NEON intrinsics when building for 32-bit ARM architecture')
option('loongarch64_mmi', type: 'feature', value: 'auto', description: 'Enable support for MMI intrinsics when building for 64-bit LoongArch architecture')
option('mips_dspr2', type: 'feature', value: 'disabled', description: 'Enable support for DSP revision 2 intrinsics when building for 32-bit MIPS architecture')
option('ppc_altivec', type: 'feature', value: 'auto', description: 'Enable support for AltiVec (Power ISA 2.05) SIMD intrinsics when building for 32-bit or 64-bit PowerPC architecture')
option('riscv_rvv', type: 'feature', value: 'auto', description: 'Enable support for RISC-V vector extension when building for 32-bit or 64-bit RISC-V architecture')
option('x86_mmx', type: 'feature', value: 'disabled', description: 'Enable support for MMX SIMD intrinsics when building for 32-bit x86 architecture')
option('x86_sse', type: 'feature', value: 'disabled', description: 'Enable support for SSE SIMD intrinsics when building for 32-bit x86 architecture')
option('x86_sse2', type: 'feature', value: 'disabled', description: 'Enable support for SSE2 SIMD intrinsics when building for 32-bit x86 architecture')
option('x86_sse3', type: 'feature', value: 'disabled', description: 'Enable support for SSE3 SIMD intrinsics when building for 32-bit x86 architecture')
option('x86_ssse3', type: 'feature', value: 'disabled', description: 'Enable support for SSSE3 SIMD intrinsics when building for 32-bit x86 architecture')
option('x86_sse41', type: 'feature', value: 'disabled', description: 'Enable support for SSE4.1 SIMD intrinsics when building for 32-bit x86 architecture')
option('x86_64_mmx', type: 'feature', value: 'auto', description: 'Enable support for MMX SIMD intrinsics when building for x86_64 architecture')
option('x86_64_sse', type: 'feature', value: 'auto', description: 'Enable support for SSE SIMD intrinsics when building for x86_64 architecture')
option('x86_64_sse2', type: 'feature', value: 'auto', description: 'Enable support for SSE2 SIMD intrinsics when building for x86_64 architecture')
option('x86_64_sse3', type: 'feature', value: 'disabled', description: 'Enable support for SSE3 SIMD intrinsics when building for x86_64 architecture')
option('x86_64_ssse3', type: 'feature', value: 'disabled', description: 'Enable support for SSSE3 SIMD intrinsics when building for x86_64 architecture')
option('x86_64_sse41', type: 'feature', value: 'disabled', description: 'Enable support for SSE4.1 SIMD intrinsics when building for x86_64 architecture')

option('angle', type: 'feature', value: 'auto', description: 'Enable support for using ANGLE to convert OpenGL calls to Direct3D, Metal or Vulkan')
option('alsa', type: 'feature', value: 'auto', description: 'Enable support for audio output via ALSA')
option('angle_direct3d9', type: 'feature', value: 'auto', description: 'Enable ANGLE\'s Direct3D 9 backend')
option('angle_direct3d11', type: 'feature', value: 'auto', description: 'Enable ANGLE\'s Direct3D 11 backend')
option('angle_metal', type: 'feature', value: 'auto', description: 'Enable ANGLE\'s Metal backend')
option('angle_null', type: 'feature', value: 'auto', description: 'Enable ANGLE\'s null backend')
option('angle_vulkan', type: 'feature', value: 'auto', description: 'Enable ANGLE\'s Vulkan backend')
option('extra_shaders', type: 'feature', value: 'auto', description: 'Enable shaders that require licensing the executable under GPLv3')
option('jack', type: 'feature', value: 'auto', description: 'Enable support for audio output via JACK Audio Connection Kit')
option('openssl', type: 'feature', value: 'auto', description: 'Enable support for HTTPS requests using OpenSSL')
option('pipewire', type: 'feature', value: 'auto', description: 'Enable support for audio output via PipeWire')
option('pulseaudio', type: 'feature', value: 'auto', description: 'Enable support for audio output via PulseAudio')

option('default_system', type: 'feature', value: 'disabled', description: 'If this is set to \'enabled\', the system versions of dependencies will be used by default; if this is set to \'disabled\', the vendored versions of dependencies will be used by default; if this is set to \'auto\', by default the system versions of dependencies that exist will be used and the vendored versions will be used otherwise; the dependency resolution behavior of individual dependencies can be overridden by explicitly setting the corresponding options to \'enabled\' or \'disabled\'')

option('alsa_system', type: 'feature', value: 'auto', description: 'Use the system version of the ALSA library instead of the vendored version')
option('fluidsynth_system', type: 'feature', value: 'auto', description: 'Use the system version of FluidSynth instead of the vendored version')
option('fmt_system', type: 'feature', value: 'auto', description: 'Use the system version of fmt instead of the vendored version')
option('freetype_system', type: 'feature', value: 'auto', description: 'Use the system version of FreeType instead of the vendored version')
option('iconv_system', type: 'feature', value: 'auto', description: 'Use the system version of iconv instead of the vendored version')
option('jack_system', type: 'feature', value: 'auto', description: 'Use the system version of the JACK Audio Connection Kit client library instead of the vendored version')
option('libffi_system', type: 'feature', value: 'auto', description: 'Use the system version of libffi instead of the vendored version')
option('libsndfile_system', type: 'feature', value: 'auto', description: 'Use the system version of libsndfile instead of the vendored version')
option('libyaml_system', type: 'feature', value: 'auto', description: 'Use the system version of libYAML instead of the vendored version')
option('ogg_system', type: 'feature', value: 'auto', description: 'Use the system version of Ogg instead of the vendored version')
option('openal_system', type: 'feature', value: 'auto', description: 'Use the system version of OpenAL instead of the vendored version')
option('openssl_system', type: 'feature', value: 'auto', description: 'Use the system version of OpenSSL instead of the vendored version')
option('physfs_system', type: 'feature', value: 'auto', description: 'Use the system version of PhysFS instead of the vendored version')
option('pipewire_system', type: 'feature', value: 'auto', description: 'Use the system version of the PipeWire client library instead of the vendored version')
option('pixman_system', type: 'feature', value: 'auto', description: 'Use the system version of Pixman instead of the vendored version')
option('pulseaudio_system', type: 'feature', value: 'auto', description: 'Use the system version of the PulseAudio client library instead of the vendored version')
option('ruby_system', type: 'feature', value: 'auto', description: 'Use the system version of Ruby instead of the vendored version')
option('sdl_image_system', type: 'feature', value: 'auto', description: 'Use the system version of SDL_image instead of the vendored version')
option('sdl_sound_system', type: 'feature', value: 'auto', description: 'Use the system version of SDL_sound instead of the vendored version')
option('sdl_system', type: 'feature', value: 'auto', description: 'Use the system version of SDL instead of the vendored version')
option('sdl_ttf_system', type: 'feature', value: 'auto', description: 'Use the system version of SDL_ttf instead of the vendored version')
option('spirv_tools_system', type: 'feature', value: 'auto', description: 'Use the system version of SPIR-V Tools instead of the vendored version')
option('theora_system', type: 'feature', value: 'auto', description: 'Use the system version of Theora instead of the vendored version')
option('uchardet_system', type: 'feature', value: 'auto', description: 'Use the system version of uchardet instead of the vendored version')
option('volk_system', type: 'feature', value: 'auto', description: 'Use the system version of volk instead of the vendored version')
option('vorbis_system', type: 'feature', value: 'auto', description: 'Use the system version of Vorbis instead of the vendored version')
option('xxhash_system', type: 'feature', value: 'auto', description: 'Use the system version of xxhash instead of the vendored version')
option('zlib_system', type: 'feature', value: 'auto', description: 'Use the system version of zlib instead of the vendored version')
