binding_sandbox_sources = files(
    'audio-binding.cpp',
    'binding-base.cpp',
    'binding-sandbox.cpp',
    'binding-util.cpp',
    'bitmap-binding.cpp',
    'etc-binding.cpp',
    'font-binding.cpp',
    'graphics-binding.cpp',
    'input-binding.cpp',
    'module_rpg.cpp',
    'plane-binding.cpp',
    'sandbox.cpp',
    'sandbox-serial-util.cpp',
    'sprite-binding.cpp',
    'table-binding.cpp',
    'tilemap-binding.cpp',
    'tilemapvx-binding.cpp',
    'viewport-binding.cpp',
    'wasi.cpp',
    'wasm-rt.cpp',
    'window-binding.cpp',
    'windowvx-binding.cpp',
)

global_sources += binding_sandbox_sources

binding_sandbox_hasher = executable(
    'binding-sandbox-hasher',
    dependencies: subproject('picosha2').get_variable('picosha2'),
    sources: 'hasher.cpp',
    native: true,
    override_options: [
        'buildtype=release',
        'b_coverage=false',
        'b_lto=false',
        'b_ndebug=false',
        'b_pgo=off',
        'b_sanitize=none',
        'cpp_std=c++11',
    ],
)

global_sources += custom_target(
    'binding-sandbox-hash',
    input: binding_sandbox_sources + [
        '../libretro/Makefile',
        '../libretro/ruby-bindings.h',
        'sandbox-serial-audio.h',
        'sandbox-serial-audiostream.h',
        'sandbox-serial-bitmap.h',
        'sandbox-serial-child-private.h',
        'sandbox-serial-core.h',
        'sandbox-serial-etc.h',
        'sandbox-serial-font.h',
        'sandbox-serial-graphics.h',
        'sandbox-serial-plane.h',
        'sandbox-serial-scene.h',
        'sandbox-serial-soundemitter.h',
        'sandbox-serial-sprite.h',
        'sandbox-serial-table.h',
        'sandbox-serial-tilemap.h',
        'sandbox-serial-tilemapvx.h',
        'sandbox-serial-viewport.h',
        'sandbox-serial-util.h',
        'sandbox-serial-wasi.h',
        'sandbox-serial-window.h',
        'sandbox-serial-windowvx.h',
    ],
    output: 'binding-sandbox-hash.h',
    command: [
        binding_sandbox_hasher,
        '@OUTPUT@',
        '@INPUT@',
    ],
)
