project('libxi', 'c', meson_version: '>=1.2.0')

libxi = declare_dependency(
    include_directories: [
        'include',
    ],
    link_with: library(
        'Xi',
        include_directories: [
            'src',
            'include',
        ],
        sources: [
            'src/XAllowDv.c',
            'src/XChDProp.c',
            'src/XChgDCtl.c',
            'src/XChgFCtl.c',
            'src/XChgKbd.c',
            'src/XChgKMap.c',
            'src/XChgPnt.c',
            'src/XChgProp.c',
            'src/XCloseDev.c',
            'src/XDelDProp.c',
            'src/XDevBell.c',
            'src/XExtToWire.c',
            'src/XGetBMap.c',
            'src/XGetCPtr.c',
            'src/XGetDCtl.c',
            'src/XGetDProp.c',
            'src/XGetFCtl.c',
            'src/XGetKMap.c',
            'src/XGetMMap.c',
            'src/XGetProp.c',
            'src/XGetVers.c',
            'src/XGMotion.c',
            'src/XGrabDev.c',
            'src/XGrDvBut.c',
            'src/XGrDvKey.c',
            'src/XGtFocus.c',
            'src/XGtSelect.c',
            'src/XListDev.c',
            'src/XListDProp.c',
            'src/XOpenDev.c',
            'src/XQueryDv.c',
            'src/XSelect.c',
            'src/XSetBMap.c',
            'src/XSetDVal.c',
            'src/XSetMMap.c',
            'src/XSetMode.c',
            'src/XSndExEv.c',
            'src/XStFocus.c',
            'src/XUngrDev.c',
            'src/XUngrDvB.c',
            'src/XUngrDvK.c',
            'src/XExtInt.c',
            'src/XIAllowEvents.c',
            'src/XIGrabDevice.c',
            'src/XIQueryVersion.c',
            'src/XIQueryDevice.c',
            'src/XISetDevFocus.c',
            'src/XIGetDevFocus.c',
            'src/XIPassiveGrab.c',
            'src/XIProperties.c',
            'src/XISelEv.c',
            'src/XISetCPtr.c',
            'src/XIWarpPointer.c',
            'src/XIHierarchy.c',
            'src/XIDefineCursor.c',
            'src/XIQueryPointer.c',
            'src/XIBarrier.c',
        ],
        dependencies: [
            dependency('inputproto', required: true),
            dependency('x11', required: true),
            dependency('xext', required: true),
            dependency('xextproto', required: true),
            dependency('xfixes', required: true),
            dependency('xproto', required: true),
        ],
    ),
    dependencies: [
        dependency('inputproto', required: true),
        dependency('x11', required: true),
        dependency('xext', required: true),
        dependency('xextproto', required: true),
        dependency('xfixes', required: true),
        dependency('xproto', required: true),
    ],
)

meson.override_dependency('xi', libxi)
