import functools
import sys

input_path = sys.argv[1]
output_path = sys.argv[2]
array_name = sys.argv[3]

size = 0

with open(input_path, 'rb') as input_file, open(output_path, 'w') as output_file:
    output_file.write('/* This file is autogenerated by tools/embedtool.py - please don\'t manually modify. */\n#ifndef MKXPZ_EMBEDTOOL_' + array_name + '\n#define MKXPZ_EMBEDTOOL_' + array_name + '\n#include <stddef.h>\n#include <stdint.h>\n#ifdef __cplusplus\nextern\n#endif /* __cplusplus */\nconst uint8_t ' + array_name + '[] = {')

    for byte in iter(functools.partial(input_file.read, 1), b''):
        if size != 0:
            output_file.write(',')
        output_file.write(str(byte[0]))
        size += 1

    output_file.write('};\n#ifdef __cplusplus\nextern\n#endif /* __cplusplus */\nconst size_t ' + array_name + '_len = ' + str(size) + 'ULL;\n#endif /* MKXPZ_EMBEDTOOL_' + array_name + ' */\n')
