embedtool = executable(
    'embedtool',
    sources: 'embedtool.cpp',
    native: true,
    override_options: [
        'buildtype=release',
        'b_coverage=false',
        'b_lto=false',
        'b_ndebug=false',
        'b_pgo=off',
        'b_sanitize=none',
        'cpp_std=c++11',
    ],
)
