import functools
import sys

input_path = sys.argv[1]
output_path = sys.argv[2]
array_name = sys.argv[3]

size = 0

with open(input_path, 'rb') as input_file, open(output_path, 'w') as output_file:
    output_file.write('/* This file is autogenerated by subprojects/common/embedtool.py - please don\'t manually modify. */\n')
    output_file.write('#ifndef MKXPZ_EMBEDTOOL_' + array_name + '\n')
    output_file.write('#define MKXPZ_EMBEDTOOL_' + array_name + '\n')
    output_file.write('#include <stddef.h>\n')
    output_file.write('#include <stdint.h>\n')
    output_file.write('#ifdef __cplusplus\n')
    output_file.write('extern\n')
    output_file.write('#endif /* __cplusplus */\n')
    output_file.write('const uint8_t ' + array_name + '[] = {')

    for byte in iter(functools.partial(input_file.read, 1), b''):
        if size != 0:
            output_file.write(',')
        output_file.write(str(byte[0]))
        size += 1

    output_file.write('};\n')
    output_file.write('#ifdef __cplusplus\n')
    output_file.write('extern\n')
    output_file.write('#endif /* __cplusplus */\n')
    output_file.write('const size_t ' + array_name + '_len = ' + str(size) + 'ULL;\n')
    output_file.write('#endif /* MKXPZ_EMBEDTOOL_' + array_name + ' */\n')
