# I have no idea what I'm doing
name: Automatic Build

on:
  push:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  pull_request:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  workflow_dispatch:

jobs:
  verify-ruby-configure-scripts:
    name: Verify Ruby 3.1 configure scripts
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:2.32.8
      options: -u root --privileged
      volumes:
        - /etc/ca-certificates:/etc/ca-certificates
        - /etc/ssl:/etc/ssl
    steps:
      - name: Checkout repository
        uses: taiki-e/checkout-action@v1

      - name: Enable Nix sandboxing
        run: |
          echo 'sandbox = true' >> /etc/nix/nix.conf

      - name: Install dependencies
        run: |
          nix-channel --add https://nixos.org/channels/nixos-25.11 nixpkgs
          nix-channel --update nixpkgs
          nix-shell -p autoconf meson --run ''

      - name: Verify
        run: |
          nix-shell -p autoconf meson --run '
            meson subprojects download ruby-3.1
            cd subprojects/ruby-3.1
            old_configure_hash="$(sha256sum configure)"
            echo "old: $old_configure_hash"
            old_config_guess_hash="$(sha256sum tool/config.guess)"
            echo "old: $old_config_guess_hash"
            old_config_sub_hash="$(sha256sum tool/config.sub)"
            echo "old: $old_config_sub_hash"
            autoreconf -fi
            new_configure_hash="$(sha256sum configure)"
            echo "new: $new_configure_hash"
            new_config_guess_hash="$(sha256sum tool/config.guess)"
            echo "new: $new_config_guess_hash"
            new_config_sub_hash="$(sha256sum tool/config.sub)"
            echo "new: $new_config_sub_hash"
            error_flag=
            if [ "$old_configure_hash" != "$new_configure_hash" ]
            then
              echo "::error::configure hash does not match"
              error_flag=1
            fi
            if [ "$old_config_guess_hash" != "$new_config_guess_hash" ]
            then
              echo "::error::tool/config.guess hash does not match"
              error_flag=1
            fi
            if [ "$old_config_sub_hash" != "$new_config_sub_hash" ]
            then
              echo "::error::tool/config.sub hash does not match"
              error_flag=1
            fi
            if [ -n "$error_flag" ]
            then
              exit 1
            fi
          '

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-git
            diffutils
            mingw-w64-x86_64-ruby
            bison
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ccache
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-meson

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/ccache
          key: win

      - name: Set up ccache
        shell: msys2 {0}
        run: |
          ccache --set-config=cache_dir='${{ runner.temp }}/ccache'
          ccache --set-config=compiler_check=content
          echo 'CCACHE_DIR=${{ runner.temp }}/ccache' >> "$GITHUB_ENV"

      - name: Configure
        shell: msys2 {0}
        run: |
          meson setup --buildtype release -Db_lto=true build

      - name: Build
        shell: msys2 {0}
        run: |
          cd build
          CLICOLOR_FORCE=1 ninja -v

      - name: Prepare archive
        shell: msys2 {0}
        run: |
          mkdir build/artifact
          cd build/artifact
          cp -r ../subprojects/ruby-3.1/dist/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../mkxp-z.exe .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .

      - name: Check for DLLs missing from the artifact
        shell: msys2 {0}
        run: |
          cd build/artifact
          error_flag=

          for file in *.exe
          do
            ldd_output="$(ldd "$file")"
            echo "$file"
            echo "$ldd_output"

            while IFS= read -r line
            do
              dll_name="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 1 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              dll_location="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 2 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              if [[ "$dll_location" = 'not found'* ]] || [[ "$dll_location" = '/mingw64/bin/'* ]] || [[ "$dll_location" = '/mingw64/lib/'* ]] || [[ "$dll_location" = '/mingw64/usr/bin/'* ]] || [[ "$dll_location" = '/mingw64/usr/lib/'* ]]
              then
                error_flag=1
                echo "::error::$dll_name is missing from the artifact"
              fi
            done <<< "$ldd_output"
          done

          if [ -n "$error_flag" ]
          then
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.windows.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-linux-native:
    name: Ubuntu 22.04 x86_64
    runs-on: ubuntu-22.04
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git diffutils ruby bison gcc g++ ccache make cmake ninja-build python3-pip
          pip3 install meson

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/ccache
          key: lin-x86_64

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir='${{ runner.temp }}/ccache'
          ccache --set-config=compiler_check=content

      - name: Configure
        run: |
          meson setup --buildtype release -Db_lto=true build

      - name: Build
        run: |
          cd build
          CLICOLOR_FORCE=1 ninja -v

      - name: Prepare archive
        run: |
          mkdir build/artifact
          cd build/artifact
          cp -r ../subprojects/ruby-3.1/dist/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../mkxp-z.x86_64 .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.linux.ubuntu.22.04.x86_64.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-linux-cross:
    name: Ubuntu 22.04 ${{matrix.arch_mkxpz}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: armv6
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
          - arch_mkxpz: armv7
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
          - arch_mkxpz: armv7-neon
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
          - arch_mkxpz: arm64
            arch_debian: arm64
            arch_gcc: aarch64-linux-gnu
          - arch_mkxpz: power8le
            arch_debian: ppc64el
            arch_gcc: powerpc64le-linux-gnu
          - arch_mkxpz: power9le
            arch_debian: ppc64el
            arch_gcc: powerpc64le-linux-gnu
          - arch_mkxpz: s390x
            arch_debian: s390x
            arch_gcc: s390x-linux-gnu
          - arch_mkxpz: riscv64
            arch_debian: riscv64
            arch_gcc: riscv64-linux-gnu
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          sudo sed -i "s/deb /deb [arch=amd64] /g" /etc/apt/sources.list
          sudo dpkg --add-architecture ${{matrix.arch_debian}}
          echo "deb [arch=${{matrix.arch_debian}}] http://ports.ubuntu.com/ jammy main restricted" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{matrix.arch_debian}}] http://ports.ubuntu.com/ jammy-updates main restricted" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{matrix.arch_debian}}] http://ports.ubuntu.com/ jammy universe" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{matrix.arch_debian}}] http://ports.ubuntu.com/ jammy-updates universe" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{matrix.arch_debian}}] http://ports.ubuntu.com/ jammy multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{matrix.arch_debian}}] http://ports.ubuntu.com/ jammy-updates multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{matrix.arch_debian}}] http://ports.ubuntu.com/ jammy-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install -y git diffutils ruby bison gcc g++ ccache make cmake ninja-build python3-pip
          pip3 install meson
          sudo apt install -y gcc-${{matrix.arch_gcc}} g++-${{matrix.arch_gcc}}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/ccache
          key: lin-${{ matrix.arch_mkxpz }}

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir='${{ runner.temp }}/ccache'
          ccache --set-config=compiler_check=content

      - name: Configure
        run: |
          meson setup --cross-file linux/meson-${{ matrix.arch_mkxpz }}.txt --buildtype release -Db_lto=true build

      - name: Build
        run: |
          cd build
          CLICOLOR_FORCE=1 ninja -v

      - name: Prepare archive
        run: |
          mkdir build/artifact
          cd build/artifact
          cp -r ../subprojects/ruby-3.1/dist/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          find .. -type f -name 'mkxp-z.*' | xargs -I {} cp {} .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.linux.ubuntu.22.04.${{matrix.arch_mkxpz}}.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-linux-native-container:
    name: Debian Trixie x86_64
    runs-on: ubuntu-22.04
    container: debian:trixie
    defaults:
      run:
        shell: bash
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          apt update
          apt install -y git diffutils ruby bison gcc g++ ccache make cmake meson

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/ccache
          key: lin-debian-trixie-x86_64

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir='${{ runner.temp }}/ccache'
          ccache --set-config=compiler_check=content

      - name: Configure
        run: |
          meson setup --buildtype release -Db_lto=true build

      - name: Build
        run: |
          cd build
          CLICOLOR_FORCE=1 ninja -v

      - name: Prepare archive
        run: |
          mkdir build/artifact
          cd build/artifact
          cp -r ../subprojects/ruby-3.1/dist/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../mkxp-z.x86_64 .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.linux.debian.trixie.x86_64.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-linux-cross-container:
    name: Debian Trixie ${{matrix.arch_mkxpz}}
    runs-on: ubuntu-22.04
    container: debian:trixie
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: armv6
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
          - arch_mkxpz: armv7
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
          - arch_mkxpz: armv7-neon
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
          - arch_mkxpz: arm64
            arch_debian: arm64
            arch_gcc: aarch64-linux-gnu
          - arch_mkxpz: power8le
            arch_debian: ppc64el
            arch_gcc: powerpc64le-linux-gnu
          - arch_mkxpz: power9le
            arch_debian: ppc64el
            arch_gcc: powerpc64le-linux-gnu
          - arch_mkxpz: s390x
            arch_debian: s390x
            arch_gcc: s390x-linux-gnu
          - arch_mkxpz: riscv64
            arch_debian: riscv64
            arch_gcc: riscv64-linux-gnu
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          dpkg --add-architecture ${{matrix.arch_debian}}
          apt update
          apt install -y git diffutils ruby bison gcc g++ ccache make cmake meson
          apt install -y gcc-${{matrix.arch_gcc}} g++-${{matrix.arch_gcc}}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/ccache
          key: lin-debian-trixie-${{ matrix.arch_mkxpz }}

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir='${{ runner.temp }}/ccache'
          ccache --set-config=compiler_check=content

      - name: Configure
        run: |
          meson setup --cross-file linux/meson-${{ matrix.arch_mkxpz }}.txt --buildtype release -Db_lto=true build

      - name: Build
        run: |
          cd build
          CLICOLOR_FORCE=1 ninja -v

      - name: Prepare archive
        run: |
          mkdir build/artifact
          cd build/artifact
          cp -r ../subprojects/ruby-3.1/dist/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          find .. -type f -name 'mkxp-z.*' | xargs -I {} cp {} .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.linux.debian.trixie.${{matrix.arch_mkxpz}}.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-macos:
    name: macOS ${{ matrix.arch_mkxpz }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: arm64
          - arch_mkxpz: x86_64
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          brew uninstall -f --ignore-dependencies git diffutils ruby bison ccache make cmake meson
          brew install -q git diffutils ruby bison ccache make cmake meson

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/ccache
          key: mac-${{ matrix.arch_mkxpz }}

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir='${{ runner.temp }}/ccache'
          ccache --set-config=compiler_check=content

      - name: Configure
        run: |
          meson setup --cross-file macos/meson-${{ matrix.arch_mkxpz }}.txt --buildtype release -Db_lto=true build

      - name: Build
        run: |
          cd build
          CLICOLOR_FORCE=1 ninja -v

      - name: Prepare archive
        run: |
          mkdir build/artifact
          cd build/artifact
          cp -r ../subprojects/ruby-3.1/dist/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          find .. -type f -name 'mkxp-z.*' | xargs -I {} cp {} .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.macos.${{ matrix.arch_mkxpz }}.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-macos-universal:
    name: macOS universal
    runs-on: macos-latest
    needs: build-macos
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Download arm64 build
        uses: actions/download-artifact@v4
        with:
          name: mkxp-z.macos.arm64.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-arm64

      - name: Download x86_64 build
        uses: actions/download-artifact@v4
        with:
          name: mkxp-z.macos.x86_64.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-x86_64

      - name: Build
        run: |
          lipo artifact-arm64/mkxp-z.aarch64 artifact-x86_64/mkxp-z.x86_64 -output artifact-arm64/mkxp-z.universal -create
          rm artifact-arm64/mkxp-z.aarch64

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.macos.universal.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-arm64
