name: Automatic Build

on:
  push:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  pull_request:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  workflow_dispatch:

jobs:
  verify-ruby-configure-scripts:
    name: Verify Ruby ${{ matrix.version }} configure scripts
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:2.34.8
      options: -u root --privileged
      volumes:
        - /etc/ca-certificates:/etc/ca-certificates
        - /etc/ssl:/etc/ssl
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 3.1
    env:
      packages: autoconf meson python3
    steps:
      - name: Checkout repository
        uses: taiki-e/checkout-action@v1

      - name: Enable Nix sandboxing
        run: |
          echo 'sandbox = true' >> /etc/nix/nix.conf

      - name: Install dependencies
        run: |
          nix-channel --add https://github.com/NixOS/nixpkgs/archive/refs/tags/26.05.tar.gz nixpkgs
          nix-channel --update nixpkgs
          nix-shell --packages $packages --run ''

      - name: Verify
        run: |
          nix-shell --packages $packages --run '
            set -eo pipefail
            meson subprojects download ruby-${{ matrix.version }}
            cd "subprojects/$(python -c "config = __import__(\"configparser\").ConfigParser(); config.read(\"subprojects/ruby-${{ matrix.version }}.wrap\"); print(config[\"wrap-file\"][\"directory\"])")"
            old_configure_hash="$(sha256sum configure)"
            echo "old: $old_configure_hash"
            old_config_guess_hash="$(sha256sum tool/config.guess)"
            echo "old: $old_config_guess_hash"
            old_config_sub_hash="$(sha256sum tool/config.sub)"
            echo "old: $old_config_sub_hash"
            autoreconf -fi
            new_configure_hash="$(sha256sum configure)"
            echo "new: $new_configure_hash"
            new_config_guess_hash="$(sha256sum tool/config.guess)"
            echo "new: $new_config_guess_hash"
            new_config_sub_hash="$(sha256sum tool/config.sub)"
            echo "new: $new_config_sub_hash"
            error_flag=
            if [ "$old_configure_hash" != "$new_configure_hash" ]
            then
              echo "::error::configure hash does not match"
              error_flag=1
            fi
            if [ "$old_config_guess_hash" != "$new_config_guess_hash" ]
            then
              echo "::error::tool/config.guess hash does not match"
              error_flag=1
            fi
            if [ "$old_config_sub_hash" != "$new_config_sub_hash" ]
            then
              echo "::error::tool/config.sub hash does not match"
              error_flag=1
            fi
            if [ -n "$error_flag" ]
            then
              exit 1
            fi
          '

  build-windows-msys2:
    name: Windows MSYS2
    runs-on: windows-latest
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            bison mingw-w64-x86_64-ccache mingw-w64-x86_64-cmake diffutils mingw-w64-x86_64-git make mingw-w64-x86_64-meson mingw-w64-x86_64-ruby
            mingw-w64-x86_64-gcc

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        if: false
        uses: actions/cache/restore@v5
        with:
          path: ccache
          key: windows-msys2-x86_64-
          restore-keys: windows-msys2-x86_64-

      - name: Set up ccache
        shell: msys2 {0}
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB
          ccache --zero-stats

      - name: Configure
        shell: msys2 {0}
        run: |
          meson setup --prefix "$(pwd)/build/artifact" --buildtype release -Dstrip=true -Db_lto=true build

      - name: Build
        id: build
        shell: msys2 {0}
        run: |
          exit_code=0
          CLICOLOR_FORCE=1 ninja -C build -v || exit_code=$?
          echo exit-code=$exit_code >> "$GITHUB_OUTPUT"
          date -u +time=%Y-%m-%dT%H:%M:%SZ >> "$GITHUB_OUTPUT"

      - name: Save to cache
        if: false
        uses: actions/cache/save@v5
        with:
          path: ccache
          key: windows-msys2-x86_64-${{ github.sha }}-${{ steps.build.outputs.time }}

      - name: Show ccache statistics
        shell: msys2 {0}
        run: |
          ccache --show-stats --verbose

      - name: Check build status
        shell: msys2 {0}
        run: |
          exit ${{ steps.build.outputs.exit-code }}

      - name: Prepare artifact
        shell: msys2 {0}
        run: |
          meson install -C build --no-rebuild --tags mkxp-z

      - name: Check for DLLs missing from the artifact
        shell: msys2 {0}
        run: |
          cd build/artifact
          error_flag=

          for file in *.exe
          do
            ldd_output="$(ldd "$file")"
            echo "$file"
            echo "$ldd_output"

            while IFS= read -r line
            do
              dll_name="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 1 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              dll_location="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 2 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              if [[ "$dll_location" = 'not found'* ]] || [[ "$dll_location" = '/mingw64/bin/'* ]] || [[ "$dll_location" = '/mingw64/lib/'* ]] || [[ "$dll_location" = '/mingw64/usr/bin/'* ]] || [[ "$dll_location" = '/mingw64/usr/lib/'* ]]
              then
                error_flag=1
                echo "::error::$dll_name is missing from the artifact"
              fi
            done <<< "$ldd_output"
          done

          if [ -n "$error_flag" ]
          then
            exit 1
          fi

  build-windows-cross:
    name: Windows ${{ matrix.arch_mkxpz }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: arm64
            clang: true
            cache: true
          - arch_mkxpz: i686
            clang: true
            cache: false
          - arch_mkxpz: x86_64
            clang: false # FIXME: x86_64 binaries built with Clang cause Ruby to crash at run time
            cache: true
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bison ccache cmake diffutils git make ruby
          # The Meson version provided by APT is too old so we install Meson using pip instead
          sudo apt install -y ninja-build python3-pip
          pip3 install meson
          sudo apt install -y gcc g++

          if [ '${{ matrix.clang }}' = 'true' ]
          then
            llvm_mingw_version=20260224-msvcrt-ubuntu-22.04-x86_64
            sudo apt install -y curl tar xz-utils
            curl --retry 5 -Lo llvm-mingw.tar.xz https://github.com/mstorsjo/llvm-mingw/releases/download/$(echo $llvm_mingw_version | cut -f 1 -d -)/llvm-mingw-$llvm_mingw_version.tar.xz
            tar -xJf llvm-mingw.tar.xz
            rm llvm-mingw.tar.xz
            mv llvm-mingw-$llvm_mingw_version ${{ runner.temp }}
            ${{ runner.temp }}/llvm-mingw-$llvm_mingw_version/bin/clang --version
            echo "PATH=${{ runner.temp }}/llvm-mingw-$llvm_mingw_version/bin:$PATH" >> "$GITHUB_ENV"
          else
            sudo apt install -y mingw-w64
          fi

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        if: ${{ matrix.cache }}
        uses: actions/cache/restore@v5
        with:
          path: ccache
          key: windows-cross-${{ matrix.arch_mkxpz }}-
          restore-keys: windows-cross-${{ matrix.arch_mkxpz }}-

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB
          ccache --zero-stats

      - name: Configure
        run: |
          if [ '${{ matrix.clang }}' = 'true' ]
          then
            compiler=clang
          else
            compiler=gcc
          fi
          meson setup --prefix "$(pwd)/build/artifact" --cross-file windows/meson-$compiler-${{ matrix.arch_mkxpz }}.txt --buildtype release -Dstrip=true -Db_lto=true build

      - name: Build
        id: build
        run: |
          exit_code=0
          CLICOLOR_FORCE=1 ninja -C build -v || exit_code=$?
          echo exit-code=$exit_code >> "$GITHUB_OUTPUT"
          date -u +time=%Y-%m-%dT%H:%M:%SZ >> "$GITHUB_OUTPUT"

      - name: Save to cache
        if: ${{ matrix.cache }}
        uses: actions/cache/save@v5
        with:
          path: ccache
          key: windows-cross-${{ matrix.arch_mkxpz }}-${{ github.sha }}-${{ steps.build.outputs.time }}

      - name: Show ccache statistics
        run: |
          ccache --show-stats --verbose

      - name: Check build status
        run: |
          exit ${{ steps.build.outputs.exit-code }}

      - name: Prepare artifact
        run: |
          meson install -C build --no-rebuild --tags mkxp-z

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.windows.${{matrix.arch_mkxpz}}.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-linux-gnu:
    name: GNU/Linux ${{ matrix.arch_mkxpz }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: armv6
            arch_debian: armhf
            cpu-family: arm
            cpu: arm
            endian: little
          - arch_mkxpz: armv7-neon
            arch_debian: armhf
            cpu-family: arm
            cpu: arm
            endian: little
          - arch_mkxpz: arm64
            arch_debian: arm64
            cpu-family: aarch64
            cpu: aarch64
            endian: little
          - arch_mkxpz: power8le
            arch_debian: ppc64el
            cpu-family: ppc64
            cpu: powerpc64le
            endian: little
          - arch_mkxpz: riscv64
            arch_debian: riscv64
            cpu-family: riscv64
            cpu: riscv64
            endian: little
          - arch_mkxpz: s390x
            arch_debian: s390x
            cpu-family: s390x
            cpu: s390x
            endian: big
          - arch_mkxpz: i386
            arch_debian: i386
            cpu-family: x86
            cpu: i386
            endian: little
          - arch_mkxpz: x86_64
            arch_debian: amd64
            cpu-family: x86_64
            cpu: x86_64
            endian: little
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bison ccache cmake diffutils git make ruby
          # The Meson version provided by APT is too old so we install Meson using pip instead
          sudo apt install -y ninja-build python3-pip
          pip3 install meson
          sudo apt install -y clang lld llvm

          if [ '${{ matrix.arch_mkxpz }}' = 'riscv64' ]
          then
            version=jammy
          else
            version=xenial
          fi
          sudo apt install -y binfmt-support curl qemu-user-static tar xz-utils
          curl --retry 5 -Lo sysroot.tar.xz https://cloud-images.ubuntu.com/$version/current/$version-server-cloudimg-${{ matrix.arch_debian }}-root.tar.xz
          mkdir ~/sysroot
          tar -xJf sysroot.tar.xz -C ~/sysroot --exclude 'dev/*'
          rm sysroot.tar.xz
          sudo mount -t devtmpfs none ~/sysroot/dev
          sudo mount -t proc none ~/sysroot/proc
          sudo mount -t tmpfs none ~/sysroot/tmp
          sudo mount -t sysfs none ~/sysroot/sys
          rm -f ~/sysroot/etc/resolv.conf
          rm -rf ~/sysroot/etc/ca-certificates/
          rm -f ~/sysroot/etc/ca-certificates.conf
          rm -rf ~/sysroot/etc/ssl/
          sudo cp /etc/resolv.conf ~/sysroot/etc/
          sudo cp -r /etc/ca-certificates ~/sysroot/etc/
          sudo cp -r /etc/ssl ~/sysroot/etc/
          PATH=/usr/sbin:/usr/bin:/sbin:/bin sudo chroot ~/sysroot /bin/bash -eo pipefail -c "
            if [ $version = xenial ] || [ $version = bionic ]
            then
              add-apt-repository -y ppa:ubuntu-toolchain-r/test || (sleep 60 && add-apt-repository -y ppa:ubuntu-toolchain-r/test || (sleep 60 && add-apt-repository -y ppa:ubuntu-toolchain-r/test || (sleep 60 && add-apt-repository -y ppa:ubuntu-toolchain-r/test || (sleep 60 && add-apt-repository -y ppa:ubuntu-toolchain-r/test))))
              apt update
              apt install -y gcc-9 g++-9
            else
              apt update
              apt install -y gcc g++
            fi
            find /lib /usr/include /usr/lib -type l -exec ln -srf {} {} \; # Convert absolute symbolic links into relative symbolic links so that they still work after we exit the chroot jail
          "

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        if: ${{ matrix.cache }}
        uses: actions/cache/restore@v5
        with:
          path: ccache
          key: linux-gnu-${{ matrix.arch_mkxpz }}-
          restore-keys: linux-gnu-${{ matrix.arch_mkxpz }}-

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB
          ccache --zero-stats

      - name: Configure
        run: |
          echo "[binaries]" | tee -a ~/cross.toml
          echo "c = ['ccache', 'clang', '--target=${{ matrix.cpu }}-linux-gnu${{ case(matrix.cpu == 'arm', 'eabihf', '') }}', '--sysroot=$(realpath ~/sysroot)']" | tee -a ~/cross.toml
          echo "c_ld = 'lld'" | tee -a ~/cross.toml
          echo "cpp = ['ccache', 'clang++', '--target=${{ matrix.cpu }}-linux-gnu${{ case(matrix.cpu == 'arm', 'eabihf', '') }}', '--sysroot=$(realpath ~/sysroot)']" | tee -a ~/cross.toml
          echo "cpp_ld = 'lld'" | tee -a ~/cross.toml
          echo "ar = 'llvm-ar'" | tee -a ~/cross.toml
          echo "ranlib = 'llvm-ranlib'" | tee -a ~/cross.toml
          echo "strip = 'llvm-strip'" | tee -a ~/cross.toml
          echo "cmake = 'cmake'" | tee -a ~/cross.toml
          echo "[host_machine]" | tee -a ~/cross.toml
          echo "system = 'linux'" | tee -a ~/cross.toml
          echo "cpu_family = '${{ matrix.cpu-family }}'" | tee -a ~/cross.toml
          echo "cpu = '${{ matrix.cpu }}'" | tee -a ~/cross.toml
          echo "endian = '${{ matrix.endian }}'" | tee -a ~/cross.toml
          if ruby -e "exit(Gem::Version.new('$(cmake --version | head -n 1 | cut -d ' ' -f 3)') < Gem::Version.new('4.0.0'))"
          then
            # This CMAKE_EXE_LINKER_FLAGS_INIT option that forces CMake to use LLD instead of the default BFD linker for CMake configure tests will not be needed once CMake updates to version 4.0.0 or later (because CMake will obey the CMAKE_EXE_LINKER_FLAGS option that we set inside of src/meson.build starting from CMake 4.0.0)
            echo "[cmake]" | tee -a ~/cross.toml
            echo "CMAKE_EXE_LINKER_FLAGS_INIT = '-fuse-ld=lld'" | tee -a ~/cross.toml
          fi
          echo '--------------------------------------------------------------------------------'
          if [ '${{ matrix.arch_mkxpz }}' = 'armv7-neon' ]
          then
            arm_neon=auto
          else
            arm_neon=disabled
          fi
          if [ '${{ matrix.arch_mkxpz }}' = 's390x' ] && ruby -e "exit(Gem::Version.new('$(clang --version | head -n 1 | sed -e 's/.*clang version * \([0-9.]*\).*/\1/')') < Gem::Version.new('19.1.0'))"
          then
            # If architecture is s390x and Clang version is older than 19.1.0, disable LTO due to https://github.com/llvm/llvm-project/issues/61101
            lto=false
          else
            lto=true
          fi
          meson setup --prefix "$(pwd)/build/artifact" --cross-file ~/cross.toml -Darm_neon=$arm_neon --buildtype release -Dstrip=true -Db_lto=$lto build

      - name: Build
        id: build
        run: |
          exit_code=0
          CLICOLOR_FORCE=1 ninja -C build -v || exit_code=$?
          echo exit-code=$exit_code >> "$GITHUB_OUTPUT"
          date -u +time=%Y-%m-%dT%H:%M:%SZ >> "$GITHUB_OUTPUT"

      - name: Save to cache
        if: ${{ matrix.cache }}
        uses: actions/cache/save@v5
        with:
          path: ccache
          key: linux-gnu-${{ matrix.arch_mkxpz }}-${{ github.sha }}-${{ steps.build.outputs.time }}

      - name: Show ccache statistics
        run: |
          ccache --show-stats --verbose

      - name: Check build status
        run: |
          exit ${{ steps.build.outputs.exit-code }}

      - name: Prepare artifact
        run: |
          meson install -C build --no-rebuild --tags mkxp-z

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.linux-gnu.${{matrix.arch_mkxpz}}.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-linux-native-container:
    name: Debian Trixie x86_64
    runs-on: ubuntu-latest
    container: debian:trixie
    defaults:
      run:
        shell: bash
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          apt update
          apt install -y bison ccache cmake diffutils git make meson ruby
          apt install -y gcc g++

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        if: false
        uses: actions/cache/restore@v5
        with:
          path: ccache
          key: debian-trixie-x86_64-
          restore-keys: debian-trixie-x86_64-

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB
          ccache --zero-stats

      - name: Configure
        run: |
          meson setup --prefix "$(pwd)/build/artifact" --buildtype release -Dstrip=true -Db_lto=true build

      - name: Build
        id: build
        run: |
          exit_code=0
          CLICOLOR_FORCE=1 ninja -C build -v || exit_code=$?
          echo exit-code=$exit_code >> "$GITHUB_OUTPUT"
          date -u +time=%Y-%m-%dT%H:%M:%SZ >> "$GITHUB_OUTPUT"

      - name: Save to cache
        if: false
        uses: actions/cache/save@v5
        with:
          path: ccache
          key: debian-trixie-x86_64-${{ github.sha }}-${{ steps.build.outputs.time }}

      - name: Show ccache statistics
        run: |
          ccache --show-stats --verbose

      - name: Check build status
        run: |
          exit ${{ steps.build.outputs.exit-code }}

      - name: Prepare artifact
        run: |
          meson install -C build --no-rebuild --tags mkxp-z

  build-linux-cross-container:
    name: Debian Trixie ${{matrix.arch_mkxpz}}
    runs-on: ubuntu-latest
    container: debian:trixie
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: armv6
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
            cache: false
          - arch_mkxpz: armv7-neon
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
            cache: false
          - arch_mkxpz: arm64
            arch_debian: arm64
            arch_gcc: aarch64-linux-gnu
            cache: false
          - arch_mkxpz: power8le
            arch_debian: ppc64el
            arch_gcc: powerpc64le-linux-gnu
            cache: false
          - arch_mkxpz: s390x
            arch_debian: s390x
            arch_gcc: s390x-linux-gnu
            cache: false
          - arch_mkxpz: riscv64
            arch_debian: riscv64
            arch_gcc: riscv64-linux-gnu
            cache: false
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          dpkg --add-architecture ${{matrix.arch_debian}}
          apt update
          apt install -y bison ccache cmake diffutils git make meson ruby
          apt install -y gcc g++
          apt install -y gcc-${{matrix.arch_gcc}} g++-${{matrix.arch_gcc}}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        if: ${{ matrix.cache }}
        uses: actions/cache/restore@v5
        with:
          path: ccache
          key: debian-trixie-${{ matrix.arch_mkxpz }}-
          restore-keys: debian-trixie-${{ matrix.arch_mkxpz }}-

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB
          ccache --zero-stats

      - name: Configure
        run: |
          if [ '${{ matrix.arch_mkxpz }}' = 'armv7-neon' ]
          then
            arm_neon=auto
          else
            arm_neon=disabled
          fi
          meson setup --prefix "$(pwd)/build/artifact" --cross-file linux/meson-${{ matrix.arch_mkxpz }}.txt -Darm_neon=$arm_neon --buildtype release -Dstrip=true -Db_lto=true build

      - name: Build
        id: build
        run: |
          exit_code=0
          CLICOLOR_FORCE=1 ninja -C build -v || exit_code=$?
          echo exit-code=$exit_code >> "$GITHUB_OUTPUT"
          date -u +time=%Y-%m-%dT%H:%M:%SZ >> "$GITHUB_OUTPUT"

      - name: Save to cache
        if: ${{ matrix.cache }}
        uses: actions/cache/save@v5
        with:
          path: ccache
          key: debian-trixie-${{ matrix.arch_mkxpz }}-${{ github.sha }}-${{ steps.build.outputs.time }}

      - name: Show ccache statistics
        run: |
          ccache --show-stats --verbose

      - name: Check build status
        run: |
          exit ${{ steps.build.outputs.exit-code }}

      - name: Prepare artifact
        run: |
          meson install -C build --no-rebuild --tags mkxp-z

  build-freebsd:
    name: FreeBSD ${{ matrix.arch }}
    runs-on: ubuntu-latest
    container: debian:latest # The base runner image's version of zstd is currently unable to extract FreeBSD's pkg files
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            cpu-family: aarch64
            cpu: aarch64
            endian: little
            sysroot-url: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/Hashed/aarch64-freebsd-sysroot-a2025.11.26_1~68315b7f42.pkg
            sysroot-hash: 68315b7f428108c9c18a6afd5e5c091ec26108180c1f2abadb7a874e21dee346
            cache: false
          - arch: amd64
            cpu-family: x86_64
            cpu: x86_64
            endian: little
            sysroot-url: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/Hashed/amd64-freebsd-sysroot-a2025.11.26_1~b5aaff1c3a.pkg
            sysroot-hash: b5aaff1c3a4ce4195c6d53fcfe018eaf88bb661b7e2cff5e8bb759f03808e279
            cache: false
          - arch: powerpc
            cpu-family: ppc
            cpu: powerpc
            endian: big
            sysroot-url: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/Hashed/powerpc-freebsd-sysroot-a2025.11.26_1~dc698d9fa7.pkg
            sysroot-hash: dc698d9fa7368b37d71e542cb466c8c009365dc6732c59052a4a997bd994776f
            cache: false
          - arch: powerpc64
            cpu-family: ppc64
            cpu: powerpc64
            endian: big
            sysroot-url: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/Hashed/powerpc64-freebsd-sysroot-a2025.11.26_1~8940892710.pkg
            sysroot-hash: 8940892710f79021b4e340285cf976d8aa4a319d3c86028bfa796d0d19d4a383
            cache: false
          - arch: powerpc64le
            cpu-family: ppc64
            cpu: powerpc64le
            endian: little
            sysroot-url: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/Hashed/powerpc64le-freebsd-sysroot-a2025.11.26_1~b90bcf67b7.pkg
            sysroot-hash: b90bcf67b79f3cd3242ee21e4287e1ee53ea5e0bd87f80aadfea0b663c6b7652
            cache: false
          - arch: riscv64
            cpu-family: riscv64
            cpu: riscv64
            endian: little
            sysroot-url: https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/Hashed/riscv64-freebsd-sysroot-a2025.11.26_1~753abe4dd5.pkg
            sysroot-hash: 753abe4dd5152870aaf1945490ba76d4ad1309b7628e3fd2bdb940068449b623
            cache: false
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        shell: bash
        run: |
          apt update
          apt install -y bison ccache cmake diffutils git make meson ruby
          apt install -y clang lld llvm

          apt install -y curl tar zstd
          curl --retry 5 -Lo sysroot.pkg '${{ matrix.sysroot-url }}'
          [ "$(sha256sum sysroot.pkg | cut -d ' ' -f 1)" = '${{ matrix.sysroot-hash }}' ]
          tar -xf sysroot.pkg --zstd
          mv usr/local/freebsd-sysroot/${{ matrix.arch }} ~/sysroot
          version=$(printf '#include <sys/param.h>\n__FreeBSD_version\n' | clang "--sysroot=$(realpath ~/sysroot)" -E - | tail -n 1)
          version_major=$((version / 100000))
          version_minor=$(((version / 1000) % 100))
          target="${{ matrix.cpu }}-unknown-freebsd$version_major.$version_minor"
          echo "Target: $target"
          echo "target=$target" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        if: ${{ matrix.cache }}
        uses: actions/cache/restore@v5
        with:
          path: ccache
          key: freebsd-${{ matrix.arch }}-
          restore-keys: freebsd-${{ matrix.arch }}-

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB
          ccache --zero-stats

      - name: Configure
        run: |
          echo "[binaries]" | tee -a ~/cross.toml
          echo "c = ['ccache', 'clang', '--target=$target', '--sysroot=$(realpath ~/sysroot)']" | tee -a ~/cross.toml
          echo "c_ld = 'lld'" | tee -a ~/cross.toml
          echo "cpp = ['ccache', 'clang++', '--target=$target', '--sysroot=$(realpath ~/sysroot)']" | tee -a ~/cross.toml
          echo "cpp_ld = 'lld'" | tee -a ~/cross.toml
          echo "ar = 'llvm-ar'" | tee -a ~/cross.toml
          echo "ranlib = 'llvm-ranlib'" | tee -a ~/cross.toml
          echo "strip = 'llvm-strip'" | tee -a ~/cross.toml
          echo "cmake = 'cmake'" | tee -a ~/cross.toml
          echo "[host_machine]" | tee -a ~/cross.toml
          echo "system = 'freebsd'" | tee -a ~/cross.toml
          echo "cpu_family = '${{ matrix.cpu-family }}'" | tee -a ~/cross.toml
          echo "cpu = '${{ matrix.cpu }}'" | tee -a ~/cross.toml
          echo "endian = '${{ matrix.endian }}'" | tee -a ~/cross.toml
          if ruby -e "exit(Gem::Version.new('$(cmake --version | head -n 1 | cut -d ' ' -f 3)') < Gem::Version.new('4.0.0'))"
          then
            # This CMAKE_EXE_LINKER_FLAGS_INIT option that forces CMake to use LLD instead of the default BFD linker for CMake configure tests will not be needed once CMake updates to version 4.0.0 or later (because CMake will obey the CMAKE_EXE_LINKER_FLAGS option that we set inside of src/meson.build starting from CMake 4.0.0)
            echo "[cmake]" | tee -a ~/cross.toml
            echo "CMAKE_EXE_LINKER_FLAGS_INIT = '-fuse-ld=lld'" | tee -a ~/cross.toml
          fi
          echo '--------------------------------------------------------------------------------'
          meson setup --prefix "$(pwd)/build/artifact" --cross-file ~/cross.toml --buildtype release -Dstrip=true -Db_lto=true build

      - name: Build
        id: build
        run: |
          exit_code=0
          CLICOLOR_FORCE=1 ninja -C build -v || exit_code=$?
          echo exit-code=$exit_code >> "$GITHUB_OUTPUT"
          date -u +time=%Y-%m-%dT%H:%M:%SZ >> "$GITHUB_OUTPUT"

      - name: Save to cache
        if: ${{ matrix.cache }}
        uses: actions/cache/save@v5
        with:
          path: ccache
          key: freebsd-${{ matrix.arch }}-${{ github.sha }}-${{ steps.build.outputs.time }}

      - name: Show ccache statistics
        run: |
          ccache --show-stats --verbose

      - name: Check build status
        run: |
          exit ${{ steps.build.outputs.exit-code }}

      - name: Prepare artifact
        run: |
          meson install -C build --no-rebuild --tags mkxp-z

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.freebsd.${{ matrix.arch }}.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-macos:
    name: macOS ${{ matrix.arch_mkxpz }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: arm64
            cache: true
          - arch_mkxpz: x86_64
            cache: true
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Install dependencies
        run: |
          brew uninstall -f --ignore-dependencies bison ccache cmake diffutils git make meson ruby
          brew install -q bison ccache cmake diffutils git make meson ruby

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore from cache
        if: ${{ matrix.cache }}
        uses: actions/cache/restore@v5
        with:
          path: ccache
          key: macos-${{ matrix.arch_mkxpz }}-
          restore-keys: macos-${{ matrix.arch_mkxpz }}-

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB
          ccache --zero-stats

      - name: Configure
        run: |
          meson setup --prefix "$(pwd)/build/artifact" --cross-file macos/meson-${{ matrix.arch_mkxpz }}.txt --buildtype release -Dstrip=true -Db_lto=true build

      - name: Build
        id: build
        run: |
          exit_code=0
          CLICOLOR_FORCE=1 ninja -C build -v || exit_code=$?
          echo exit-code=$exit_code >> "$GITHUB_OUTPUT"
          date -u +time=%Y-%m-%dT%H:%M:%SZ >> "$GITHUB_OUTPUT"

      - name: Save to cache
        if: ${{ matrix.cache }}
        uses: actions/cache/save@v5
        with:
          path: ccache
          key: macos-${{ matrix.arch_mkxpz }}-${{ github.sha }}-${{ steps.build.outputs.time }}

      - name: Show ccache statistics
        run: |
          ccache --show-stats --verbose

      - name: Check build status
        run: |
          exit ${{ steps.build.outputs.exit-code }}

      - name: Prepare artifacts
        run: |
          meson install -C build --no-rebuild --tags mkxp-z-bundle
          mv build/artifact build/artifact-bundle
          meson install -C build --no-rebuild --tags mkxp-z

      - name: Upload standalone artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.macos.${{ matrix.arch_mkxpz }}.standalone.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.macos.${{ matrix.arch_mkxpz }}.app.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact-bundle

  build-macos-universal:
    name: macOS universal
    runs-on: macos-latest
    needs: build-macos
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Download arm64 standalone artifact
        uses: actions/download-artifact@v4
        with:
          name: mkxp-z.macos.arm64.standalone.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-arm64

      - name: Download arm64 bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: mkxp-z.macos.arm64.app.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-bundle-arm64

      - name: Download x86_64 standalone artifact
        uses: actions/download-artifact@v4
        with:
          name: mkxp-z.macos.x86_64.standalone.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-x86_64

      - name: Download x86_64 bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: mkxp-z.macos.x86_64.app.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-bundle-x86_64

      - name: Build
        run: |
          lipo artifact-arm64/mkxp-z.aarch64 artifact-x86_64/mkxp-z.x86_64 -output mkxp-z.universal -create
          cp -p -R artifact-arm64/* artifact-x86_64/
          mv artifact-x86_64 artifact
          rm artifact/mkxp-z.aarch64
          rm artifact/mkxp-z.x86_64
          mv mkxp-z.universal artifact/
          lipo artifact-bundle-arm64/mkxp-z.aarch64.app/Contents/MacOS/bundle_mkxp-z artifact-bundle-x86_64/mkxp-z.x86_64.app/Contents/MacOS/bundle_mkxp-z -output bundle_mkxp-z -create
          mv artifact-bundle-arm64/mkxp-z.aarch64.app artifact-bundle-arm64/mkxp-z.universal.app
          mv artifact-bundle-x86_64/mkxp-z.x86_64.app artifact-bundle-x86_64/mkxp-z.universal.app
          cp -p -R artifact-bundle-arm64/* artifact-bundle-x86_64/
          mv artifact-bundle-x86_64 artifact-bundle
          mv bundle_mkxp-z artifact-bundle/mkxp-z.universal.app/Contents/MacOS/

      - name: Upload standalone artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.macos.universal.standalone.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.macos.universal.app.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: artifact-bundle
